- name: 20-Deploy Package
  hosts: win
  gather_facts: false
  vars_files:
    - Deployment_Variables.txt
  vars:
    iis_configuration_json: "{{ lookup('file', 'iis-website-config.json') | from_json }}"
    current_package_basename: "{{ iis_configuration_json.PhysicalPath | regex_search('\\w+$') }}"
    binding_port: "{{ iis_configuration_json.Bindings | regex_search('\\d+') }}"

  tasks:
    - name: "Register {{ app_name }} Current Package Folder stat into Ansible Variable"
      win_stat:
        path: "{{ iis_configuration_json.PhysicalPath }}\\"
      register: current_package_folder_stat

    - name: Fail if {{ app_name }} Current Package Folder doesn't exists on IIS path
      ansible.builtin.fail:
        msg: "Current Package Folder doesn't exists in \\wwwroot path"
      when: current_package_folder_stat.stat.exists != true

    - name: "Register {{ app_name }} New Package Folder stat into Ansible Variable"
      win_stat:
        path: "{{ local_deployment_package_path }}\\{{ current_package_basename }}\\"
      register: new_package_folder_stat

    - name: Fail if {{ app_name }} New Package Folder doesn't exists on Deployments Folder
      ansible.builtin.fail:
        msg: "New Package Folder doesn't exists in Deployments Folder"
      when: new_package_folder_stat.stat.exists != true

    - name: Copy '{{ app_name }}' current package folder to '{{ app_name }}_{{ timestamp }}' folder for Rollback
      win_copy:
        remote_src: true
        src: "{{ iis_configuration_json.PhysicalPath }}\\"
        dest: "{{ iis_configuration_json.PhysicalPath }}_{{ timestamp }}"

    - name: "Delete '{{ app_name }}' current package Folder"
      win_file:
        path: "{{ iis_configuration_json.PhysicalPath }}"
        state: absent

    - name: Copy '{{ app_name }}' New Package folder from Deployments Folder to '{{ app_name }}' folder
      win_copy:
        remote_src: yes
        src: "{{ local_deployment_package_path }}\\{{ current_package_basename }}\\"
        dest: "{{ iis_configuration_json.PhysicalPath }}\\"

    - name: "Ensure '{{ iis_configuration_json.applicationPool }}' is Restarted"
      community.windows.win_iis_webapppool:
        name: "{{ iis_configuration_json.applicationPool }}"
        state: restarted

    - name: "Send GET Request to '{{ app_name }}' main page and ensure '200' is returned"
      win_uri:
        url: "http://localhost:{{ binding_port }}"
      register: get_request_reponse

    - name: "Print Get Response status code"
      debug:
        var: get_request_reponse.status_code

    - name: "Fail if '{{ app_name }}'' response status code != '200'"
      ansible.builtin.fail:
        msg: "{{ app_name }} response status code != '200', New Package Deployment failed"
      when: get_request_reponse.status_code != 200

    - name: "Cleanup - Delete '{{ app_name }}_{{ timestamp }}'' Rollback Folder"
      win_file:
        path: "{{ iis_configuration_json.PhysicalPath }}_{{ timestamp }}"
        state: absent
      when: get_request_reponse.status_code == 200